### ISSUE TITLE
Consider adding a default category for "Grip & Electric"?

### ISSUE THREAD

**Issue by ldeboer** [UniversalScheduleStandard/UniversalCategoryIdentification#1]
It's my understanding that the universal category identification library is extendable by individual users, however, I'm wondering about adding a dedicated default category for "Grip & Electric". (Could also be named G&E?) Perhaps this would not be necessary if utilizing the "special equipment" category to denote things that might be needed such as condors, or certain light arrays. But I could also see there being a use-case for keeping grip and electric notes/equipment separate from other specialty equipment that might be needed on a shoot.

For instance, in very complex setups that will require special planning for G&E to execute the lighting setup, might be nice to have a dedicated spot to place those notes. (Example: "Pre-rig this setup before shooting day" or "Rig a light on a movable gimbal to achieve drive-by effect")

Just a thought for consideration. 

Thanks for all the effort you've put into this!
Luke @ SetHero ([luke@setheroapp.com](mailto:luke@setheroapp.com))

**Comment by modemmute** [comment]
This is an interesting suggestion and could be potentially useful. But some thoughtful consideration should be employed here.

One of the important things to keep in mind when creating standards in the film industry is its long and complicated history. The categories currently proposed in this standard generally conform the long standing list of categories that were historically used by many studios and assistant directors throughout history. When the first schedule software was written in the early 1990's, that software generally conformed to that well used list of categories. 

Subsequently the list of categories in this proposed standard roughly correspond to the ones used in Movie Magic Scheduling, Think Crew, Final Draft and many others. See [this example](https://github.com/UniversalScheduleStandard/UniversalCategoryIdentification/blob/dc7420a70fc72d4c108fbc184e889f3495f1b533/reference/finalDraftCategories.xml) in the reference folder of this repository. 

All of that said, the importance of both the grip and electric departments have grown considerably over the last 30 years. The quantity of specialty equipment utilized by those departments is likely exponentially larger than would have been possible in the 80's, or before. They also are the only major departments on a show to not have their own category representation in the current list. 

I think there's a good case to be made to permanently include one `Grip & Electric` category to the standard. Further, it might be worthwhile to entertain arguments about adding both categories individually to the standard - should anyone care to make those arguments here.

**Comment by modemmute** [comment]
With no more comments on this topic, I'll be implementing your suggestion and am closing the issue.
